
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv
import sys

# do not edit this file, it is generated by generator.py

def update(mf_struct, gv, cur):
    for f in list(mf_struct.keys()):
        if gv in f:
            if "count" in f:
                mf_struct[f] += 1
            if "max" in f:
                mf_struct[f] = max(mf_struct[f], cur)
            if "min" in f:
                mf_struct[f] = min(mf_struct[f], cur)
            if "avg" in f:
                if "count" not in mf_struct:
                    mf_struct['count'] = 1
                    mf_struct[f] = cur
                else:
                    mf_struct['count'] += 1
                    mf_struct[f] = (mf_struct[f] * (mf_struct['count']-1) + cur) / mf_struct['count']
            if "sum" in f:
                mf_struct[f] += cur

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    rows = cur.fetchall()
    
    if not rows:
        print("No data found.")
        return ""

    
    _global = []
    
    mf_structs = {}
    for row in rows:
        if row['prod'] not in mf_structs:
            
            mf_struct = {}
            mf_struct['max_1_quant'] = 0
            mf_struct['min_1_quant'] = sys.maxsize
            mf_struct['max_2_quant'] = 0
            mf_struct['min_2_quant'] = sys.maxsize
            mf_structs[row['prod']] = mf_struct
    
    
    for row in rows:
        if row['state'] == 'NY':
            if row['prod'] in mf_structs:
                update(mf_structs[row['prod']], '1', row['quant'])
        
    for row in rows:
        if row['state'] == 'NJ':
            if row['prod'] in mf_structs:
                update(mf_structs[row['prod']], '2', row['quant'])
        
    for mf_struct in list(mf_structs.values()):
        mf_struct.pop('count', None)
    
    #print(mf_structs)

    # output mf_structs (append to _global)
    for key, mf_struct in mf_structs.items():
        row_dict = {'prod': key}
        for f in mf_struct.keys():
            row_dict[f] = mf_struct[f]
        _global.append(row_dict)
    
    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql")

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    