
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    rows = cur.fetchall()
    
    _global = []
    
    mf_struct = {}
    mf_struct['cust'] = []
    mf_struct['count_1_quant'] = 0
    mf_struct['sum_2_quant'] = 0
    mf_struct['max_3_quant'] = 0
    
    for row in rows:
        if row['cust'] not in mf_struct['cust']:
            mf_struct['cust'] += [row['cust']]
    
    print(mf_struct)
    
    for row in rows:
        if row['quant'] > 10:
            _global.append(row)
    
    
    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql")

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    