import subprocess

def mf_struct(phi):
    result = """
            mf_struct = {}"""
    for f in phi.f_vect:
        result += f"""
            mf_struct['{f}'] = 0"""
    return result

def populate(phi):
    '''# TABLE SCAN 1: populate mf-struct with distinct values of grouping attribute (V)'''
    gb = phi.v[0] # group by attribute
    result = """
    mf_structs = {}"""
    result += f"""
    for row in rows:
        if row['{gb}'] not in mf_structs:
            {mf_struct(phi)}
            mf_structs[row['{gb}']] = mf_struct
    """
    return result

def gv_scan(phi):
    gb = phi.v[0] # group by attribute
    result = """"""
    for pred in phi.pred_list:
        gv = pred.split('.')[0]
        condition = pred.split('.')[1].split(' ')
        aggregate = condition[0]
        bool = " ".join(condition[1:])

        result += f"""
    for row in rows:
        if row['{aggregate}'] {bool}:
            # update mf-struct
        """
    
    return result

def generate(phi, output_file=None):
    tmp = f"""
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def update(pred, mf_struct, gv, cur):
    for f in list(mf_struct.keys()):
        if gv in f:
            if "count" in pred:
                mf_struct[f] += 1
            if "max" in pred:
                mf_struct[f] = max(mf_struct[f], cur)
            if "min" in pred:
                mf_struct[f] = min(mf_struct[f], cur)
            if "avg" in pred:
                if "count" not in mf_struct:
                    mf_struct['count'] = 1
                    mf_struct[f] = cur
                else:
                    mf_struct['count'] += 1
                    mf_struct[f] = (mf_struct[f] * (mf_struct['count']-1) + cur) / mf_struct['count']
            if "sum" in pred:
                mf_struct[f] += cur

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    rows = cur.fetchall()
    
    _global = []
    {populate(phi)}
    {gv_scan(phi)}

    # output mf_structs (append to _global)
    
    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql")

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    """

    # Write the generated code to a file
    open("_generated.py", "w").write(tmp)
    # Execute the generated code

    # if using environment using conda installed by brew, then uncomment the following line
    # and comment the next line
    # subprocess.run(["/opt/homebrew/anaconda3/bin/python", "_generated.py"])
    if output_file:
        result = subprocess.run(["/opt/homebrew/anaconda3/bin/python", "_generated.py"], capture_output=True, text=True)
        with open(output_file, "w+") as f:
            f.write(result.stdout)
            if result.stderr:
                f.write(result.stderr)
    else:
        subprocess.run(["/opt/homebrew/anaconda3/bin/python", "_generated.py"])
